AllCops:
  Include:
    - '**/*.rb'
  TargetRubyVersion: 2.3


Gemspec/DuplicatedAssignment:
  Enabled: false


Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Exclude:
    - 'spec/**/*_spec.rb'

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false


Layout/AlignArguments:
  EnforcedStyle: with_fixed_indentation

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Layout/SpaceInsideBlockBraces:
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: no_space
  SpaceBeforeBlockParameters: false

Layout/CaseIndentation:
  EnforcedStyle: end
  SupportedStyles:
    - case
    - end
  IndentOneStep: true


Naming/FileName:
  Exclude:
    - Appraisals
    - Gemfile
    - Rakefile
    - rails-etcs.gemspec


Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent

Style/RaiseArgs:
  EnforcedStyle: compact

Style/Documentation:
  Enabled: false

Style/SignalException:
  EnforcedStyle: only_raise

Style/ClassAndModuleChildren:
  Enabled: false

Style/TrivialAccessors:
  AllowPredicates: true
