sudo: false
language: ruby
bundler_args: "--without development"
rvm:
- '2.3.1'
- '2.2.5'
- '2.1'
- '2.0'
- '1.9.3'
- 'jruby'
- 'rbx-2'
matrix:
  allow_failures:
  - rvm: jruby
  - rvm: rbx-2
script:
- bundle exec rspec
- bundle exec gurke
