sudo: false
language: ruby
bundler_args: "--without development"
rvm:
- 2.6.1
- 2.5.3
- 2.4.5
- 2.3.8
script:
- bundle exec rubocop
- bundle exec rspec
- bundle exec gurke -f compact
jobs:
  include:
  - stage: Release
    rvm: 2.6.1
    script: skip
    install: skip
    deploy:
      provider: rubygems
      api_key:
        secure: IYfcBZnl7cESAIa5YQevFjD75YWCT1ROoANWCuuyrTNcKnWa43PGuOdVsgNiyU7mBmcYaqb3TI2vQHMrcQ8tNHyrgDyV3OUsJBnZZtO3Q5bxEdrjtqURTfmKMhkqyntdXTYQlM0s+WPirayzuidnA0D3FQThxaBqpTjHOtW+6KM=
      gem: gurke
      on:
        tags: true
        repo: jgraichen/gurke
