dist: bionic
language: ruby
bundler_args: "--without development"
rvm:
  - 2.7.1
  - 2.6.6
  - 2.5.8
script:
  - bundle exec rspec --color
  - bundle exec gurke -f compact
jobs:
  include:
    - name: rubocop
      rvm: 2.7.1
      script: bundle exec rubocop --parallel --color
