name: test
on:
  - push
  - pull_request
jobs:
  test:
    name: Ruby ${{ matrix.ruby }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby:
          - "3.3"
          - "3.2"
          - "3.1"
          - "3.0"
          - "2.7"
      fail-fast: false

    env:
      BUNDLE_WITHOUT: development
      BUNDLE_RETRY: 3
      BUNDLE_JOBS: 4

    steps:
      - uses: actions/checkout@master
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "${{ matrix.ruby }}"
          bundler-cache: True

      - run: bundle exec rspec --color
      - run: bundle exec gurke --formatter compact

      - uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  rubocop:
    name: rubocop
    runs-on: ubuntu-24.04

    env:
      BUNDLE_WITHOUT: test
      BUNDLE_RETRY: 3
      BUNDLE_JOBS: 4

    steps:
      - uses: actions/checkout@master
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3.5"
          bundler-cache: True

      - name: Run rubocop
        run: bundle exec rubocop --parallel --color
